services:
  - type: web
    name: frammer-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: frammer-dashboard
    runtime: static
    rootDir: frontend
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://frammer-api.onrender.com/api
